### ISSUE TITLE
这个是发现的问题 有空可以处理下，今天测试了部分发现的。

### ISSUE THREAD

**Issue by lip5201** [smalls0098/origin-php-watermark-api#3]
1.腾讯视频返回错误
http://m.v.qq.com/play/play.html?vid=q3115syabis&url_from=share&second_share=0&share_from=copy&pgid=page_smallvideo_immersive&ztid=120136&mod_id=sp_immersive_poster

返回信息
{
	"status": false,
	"data": "ErrorVideo : 获取不到vid参数信息"
}
2.bilibili 返回的是空的视频
https://b23.tv/2rVNfX

返回信息
{
	"status": true,
	"data": {
		"md5": "02c599e9a09bfc25aebe7ec942b354f0",
		"message": "https:\/\/b23.tv\/2rVNfX",
		"user_name": "",
		"user_head_img": "",
		"desc": "",
		"img_url": "",
		"video_url": "http:\/\/upos-sz-mirrorhw.bilivideo.com\/upgcxcode\/80\/36\/210443680\/210443680_nb2-1-32.flv?e=ig8euxZM2rNcNbRz7WdVhoM1hzUVhwdEto8g5X10ugNcXBlqNxHxNEVE5XREto8KqJZHUa6m5J0SqE85tZvEuENvNo8g2ENvNo8i8o859r1qXg8xNEVE5XREto8GuFGv2U7SuxI72X6fTr859r1qXg8gNEVE5XREto8z5JZC2X2gkX5L5F1eTX1jkXlsTXHeux_f2o859IB_&uipk=5&nbs=1&deadline=1595861057&gen=playurl&os=hwbv&oi=2067390100&trid=9754dc400f7f4daaa4ddd8799a47c029u&platform=pc&upsig=63d55683f54e67d782b98e624b21de4d&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,platform&mid=0&orderid=0,3&logo=80000000",
		"type": "video"
	}
}

3. 最右返回错误
https://share.izuiyou.com/hybrid/share/post?pid=141822110&zy_to=applink&share_count=1&m=c62016eadcf95203dbae83f988e99ce0&d=5fbb3318f220ee837731bba0370f49df718aca08a5919194a78432ebfc4cf40fb110fd96bfaffc80d32837ce18fbf743&app=zuiyou&recommend=top_ctr&name=use_push_only&title_type=post

返回信息
{
	"status": false,
	"data": "ErrorVideo : 获取不到pid参数信息"
}

4.刷宝的错误
http://m.shua8cn.com/cVId3f
返回信息
{
	"status": false,
	"data": "ErrorVideo : URL校验失败"
}

路径 \video-tools\config\url-validator.php 的URL shua8cn.com/video_share改回shua8cn.com后
返回信息
{
	"status": false,
	"data": "ErrorVideo : 获取不到show_id参数信息"
}

**Comment by smalls0098** [comment]
好的呢，你这个issues对我贡献很大，相比其他只是反馈给我哪个错误，我完全不知道什么问题
